# Generated by Django 5.1.4 on 2025-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gallery_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_pic"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participant_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guest",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_pic"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_pic"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="img",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="events_img"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="vid",
            field=models.FileField(
                blank=True, default="default.mp4", upload_to="events_video"
            ),
        ),
    ]
