# Generated by Django 5.1.4 on 2025-01-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contact_profile_img_event_participant_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="guest",
            field=models.ManyToManyField(related_name="events", to="core.guest"),
        ),
        migrations.AlterField(
            model_name="guest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="core.event",
            ),
        ),
    ]
