# Generated by Django 5.1.4 on 2025-01-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_guest_alter_guest_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slung",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
