# Generated by Django 5.1.4 on 2025-01-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_event_slung"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slung",
        ),
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
