# Generated by Django 5.1.4 on 2025-01-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_activities_delete_highlight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="event",
        ),
    ]
