# Generated by Django 5.1.4 on 2025-01-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_guest_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cultural", "Cultural"),
                            ("Technical", "Technical"),
                            ("Sports", "Sports"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "vid_reg",
                    models.FileField(default="default.mp4", upload_to="carousel"),
                ),
                (
                    "vid_carousel",
                    models.FileField(default="default.mp4", upload_to="carousel"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="summary",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cultural", "Cultural"),
                    ("Technical", "Technical"),
                    ("Sports", "Sports"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="activities",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.event",
            ),
        ),
    ]
