# Generated by Django 5.1.4 on 2025-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_carousel_remove_event_summary_event_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(blank=True, upload_to="gallery/"),
        ),
    ]
