# Generated by Django 5.1.4 on 2025-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_event_date_alter_gallery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="venue",
            field=models.TextField(blank=True, default="VIT Campus Gate 2"),
        ),
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
